"""Shared PDF infrastructure for cache management and document setup."""

import hashlib
import logging
import os
import shutil
import tempfile
import time
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

logger = logging.getLogger(__name__)


class PDFBase:
    CACHE_TTL_SECONDS = 3600

    def __init__(self, cache_dir: str | None = None):
        if cache_dir is None:
            base = Path(os.environ.get("DATA_DIR", tempfile.gettempdir()))
            cache_dir = str(base / "pdf_cache")
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(mode=0o700, exist_ok=True)
        self.styles = getSampleStyleSheet()

    def _evict_stale_cache(self) -> None:
        cutoff = time.time() - self.CACHE_TTL_SECONDS
        try:
            for entry in self.cache_dir.iterdir():
                if entry.is_file() and entry.stat().st_mtime < cutoff:
                    entry.unlink(missing_ok=True)
        except OSError:
            pass

    def _cache_key_from_hash(self, prefix: str, plan_id, content) -> str:
        if not isinstance(content, str):
            import json

            content = json.dumps(content, sort_keys=True)
        content_hash = hashlib.md5(content.encode()).hexdigest()
        return f"{prefix}{plan_id}_{content_hash}.pdf"

    def _build_doc(self, path: str) -> SimpleDocTemplate:
        return SimpleDocTemplate(
            path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

    def _generate_with_cache(self, cache_key: str, filename: str, build_fn) -> str:
        self._evict_stale_cache()
        cache_path = self.cache_dir / cache_key

        if cache_path.exists():
            logger.info(f"Using cached PDF: {cache_key}")
            return str(cache_path)

        logger.info(f"Generating new PDF: {cache_key}")
        temp_dir = tempfile.mkdtemp()
        pdf_path = os.path.join(temp_dir, filename)

        doc = self._build_doc(pdf_path)
        story: list = []
        build_fn(doc, story)
        doc.build(story)

        shutil.move(pdf_path, cache_path)
        shutil.rmtree(temp_dir, ignore_errors=True)
        return str(cache_path)

    def _build_footer(self, story: list, text: str = "Generated by RunCoach") -> None:
        story.append(Spacer(1, 1 * cm))
        footer_style = ParagraphStyle(
            "Footer",
            parent=self.styles["Normal"],
            fontSize=7,
            alignment=TA_CENTER,
            textColor=colors.gray,
        )
        story.append(Paragraph(text, footer_style))
        story.append(
            Paragraph(
                "Consult a sports medicine professional before starting any new training programme.",
                footer_style,
            )
        )
