"""PDF supplementary pages — injury prevention, footer."""

from typing import List

from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER


class SupplementaryPagesMixin:
    """Methods for rendering supplementary PDF pages."""

    def _add_injury_prevention(self, story: List):
        story.append(Paragraph("🏥 Complete Injury Prevention Guide", self.section_style))

        story.append(Paragraph("🔥 Warm-up Protocol (10-15 minutes)", self.normal_style))
        for step in [
            "Dynamic Stretches: Leg swings, walking lunges, high knees (5 minutes)",
            "Activation Exercises: Glute bridges, monster walks (3 minutes)",
            "Progressive Run: Walk 2min → jog 3min → run 5min (5 minutes)",
            "Sport-Specific Drills: A-skips, B-skips, butt kicks (2 minutes)"
        ]:
            story.append(Paragraph(f"• {step}", self.small_style))
        story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("❄️ Cool-down Protocol (10-15 minutes)", self.normal_style))
        for step in [
            "Active Recovery: Easy walk or jog (5 minutes)",
            "Static Stretches: Hold each 30 seconds, no bouncing",
            "Focus Areas: Hamstrings, quads, calves, hips, IT band",
            "Foam Rolling: 1-2 minutes per muscle group"
        ]:
            story.append(Paragraph(f"• {step}", self.small_style))
        story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("💪 Essential Strength Training (2-3x per week)", self.normal_style))
        for exercise in [
            "Lower Body: Squats (3x12), Lunges (3x10 each), Calf raises (3x20)",
            "Core: Plank (3x45sec), Side planks (3x30sec each), Dead bugs (3x10 each)",
            "Hip Stability: Clamshells (3x15 each), Glute bridges (3x15), Monster walks (3x10 each)",
            "Upper Body: Push-ups (3x10), Rows (3x12), Overhead press (3x10)"
        ]:
            story.append(Paragraph(f"• {exercise}", self.small_style))
        story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("🛌 Recovery Strategies", self.normal_style))
        for tip in [
            "Sleep: 7-9 hours nightly, consistent schedule",
            "Nutrition: Protein within 30 minutes post-run, anti-inflammatory foods",
            "Hydration: 2-3L daily + electrolytes on long run days",
            "Active Recovery: Swimming, cycling, yoga on rest days",
            "Massage: Professional monthly + self-massage weekly"
        ]:
            story.append(Paragraph(f"• {tip}", self.small_style))
        story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("⚠️ Warning Signs - When to Stop", self.normal_style))
        for sign in [
            "Pain that increases during run (vs. decreases with warm-up)",
            "Sharp, stabbing, or localized pain",
            "Pain that causes limping or form changes",
            "Swelling, redness, or warmth in joints/tissues",
            "Pain that persists >24 hours after rest",
            "Night pain or pain at rest"
        ]:
            story.append(Paragraph(f"• {sign}", self.small_style))
        story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("👟 Equipment Management", self.normal_style))
        for tip in [
            "Running Shoes: Replace every 500-800km or 6-12 months",
            "Rotation: Have 2+ pairs, alternate to extend life",
            "Proper Fit: Shop in afternoon, thumb-width space at toe",
            "Surface-Specific: Road shoes for pavement, trail shoes for off-road",
            "Monitoring: Check for uneven wear patterns, midsole compression"
        ]:
            story.append(Paragraph(f"• {tip}", self.small_style))
        story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("📈 Smart Training Progression", self.normal_style))
        for rule in [
            "10% Rule: Increase weekly mileage by max 10% every 2-3 weeks",
            "Recovery Weeks: Reduce mileage by 20-30% every 4th week",
            "Hard/Easy Balance: Follow hard days with easy or rest days",
            "Listen to Body: Use perceived exertion scale 1-10, stay at 6-7 for easy runs",
            "Cross-Training: Replace 1-2 runs weekly with low-impact activities"
        ]:
            story.append(Paragraph(f"• {rule}", self.small_style))
        story.append(Spacer(1, 1 * cm))

    def _add_footer(self, story: List):
        story.append(Spacer(1, 1 * cm))
        story.append(Paragraph(
            "Generated by RunCoach - Your Personalized Running Training Plan Generator",
            ParagraphStyle('Footer', parent=self.styles['Normal'], fontSize=8,
                          alignment=TA_CENTER, textColor=colors.gray)))
        story.append(Paragraph(
            "Consult with a healthcare professional before beginning any new training program",
            ParagraphStyle('Footer2', parent=self.styles['Normal'], fontSize=8,
                          alignment=TA_CENTER, textColor=colors.gray)))
