"""Per-distance race profiles for the road race-day protocol.

Centralises the distance-specific data that used to live in five parallel
dicts in `race_protocol_generator` (display name, pacing strategy,
nutrition timing, mental checkpoints, race-morning timeline, week-before
extras). Adding a new road race distance is now one registry entry rather
than five scattered dict updates.

Trail / ultra protocols remain procedurally generated by
`race_protocol_generator` (their content scales with distance, elevation,
and predicted duration). Trail still consumes
`RACE_PROFILES[30.0].pacing_strategy` as the base copy plus its own
bracket-specific extras.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class RaceProfile:
    """Distance-specific race-day content.

    `distance_km` is the canonical race distance.
    `display_name` is the user-facing label ("5K", "Half Marathon", …).
    `pacing_strategy` is the prose paragraph rendered in the race-day card.
    `nutrition_timing` / `mental_checkpoints` / `morning_timeline` /
    `week_before_extras` are the per-section payloads consumed by the
    template.
    """
    distance_km: float
    display_name: str
    pacing_strategy: str
    nutrition_timing: List[Dict[str, str]]
    mental_checkpoints: List[Dict[str, str]]
    morning_timeline: List[Tuple[str, str]]
    week_before_extras: List[str] = field(default_factory=list)


_5K = RaceProfile(
    distance_km=5.0,
    display_name="5K",
    pacing_strategy=(
        "Start 3–5 sec/km slower than goal pace for the first 1 km to avoid blowing up. "
        "Settle into goal pace by km 2. Give everything in the final km. "
        "A 5K is an aerobic sprint — controlled aggression from the gun."
    ),
    nutrition_timing=[
        {"icon": "🍌", "when": "2–3 hrs before", "what": "Light carb meal (toast, banana, oats)"},
        {"icon": "💧", "when": "30 min before", "what": "200–300 ml water"},
        {"icon": "🏃", "when": "During race", "what": "No fueling needed for most runners"},
        {"icon": "🍫", "when": "Immediately after", "what": "Simple carbs + protein within 30 min"},
    ],
    mental_checkpoints=[
        {"distance": "1 km", "message": "Settle in. Ignore the adrenaline — run your pace."},
        {"distance": "2.5 km", "message": "Halfway. How do you feel? If easy, stay patient. If hard, focus on form."},
        {"distance": "4 km", "message": "One km left. This is what you trained for — find another gear."},
        {"distance": "Finish", "message": "Empty the tank. Sprint or try to sprint — leave nothing behind."},
    ],
    morning_timeline=[
        ("2 hrs before", "Wake up and eat pre-race meal"),
        ("90 min before", "Arrive at venue, collect bib"),
        ("45 min before", "Light dynamic warm-up: leg swings, A-skips, strides"),
        ("15 min before", "Final bathroom stop, drop bag, move to start"),
        ("5 min before", "Easy jog 2–3 min, shake out the legs"),
    ],
)


_10K = RaceProfile(
    distance_km=10.0,
    display_name="10K",
    pacing_strategy=(
        "First 2 km: run goal pace minus 3–5 sec/km. "
        "Km 3–8: lock into goal pace and hold it. "
        "Final 2 km: dig in — if you have anything left, use it now. "
        "The 10K rewards patience in the first half."
    ),
    nutrition_timing=[
        {"icon": "🍌", "when": "2–3 hrs before", "what": "Light carb meal (toast, banana, oats)"},
        {"icon": "💧", "when": "30 min before", "what": "200–300 ml water"},
        {"icon": "💧", "when": "At 5 km", "what": "Water at aid station (hot day: take it)"},
        {"icon": "🍫", "when": "Within 30 min after", "what": "Protein + carbs for recovery"},
    ],
    mental_checkpoints=[
        {"distance": "2 km", "message": "Resist the urge to race others. Lock into your goal pace."},
        {"distance": "5 km", "message": "Halfway. Reassess: can you sustain this to the finish?"},
        {"distance": "8 km", "message": "The real race starts now. Every step matters."},
        {"distance": "9 km", "message": "One km. Trust your training and push."},
    ],
    morning_timeline=[
        ("2 hrs before", "Wake up and eat pre-race meal"),
        ("90 min before", "Arrive at venue, collect bib, walk the start area"),
        ("45 min before", "10 min easy jog + dynamic drills (high knees, butt kicks)"),
        ("20 min before", "4–6 × 20-sec strides at goal pace"),
        ("10 min before", "Final bathroom, move to corral"),
    ],
)


_HALF = RaceProfile(
    distance_km=21.1,
    display_name="Half Marathon",
    pacing_strategy=(
        "First 5 km: goal pace minus 5–8 sec/km — resist the crowd. "
        "Km 5–16: settle into goal pace, focus on smooth, relaxed running. "
        "Km 16–21: the real race begins — draw on your training and execute. "
        "Negative splits (faster second half) produce the best results."
    ),
    nutrition_timing=[
        {"icon": "🍌", "when": "3 hrs before", "what": "Tested pre-race meal (oats, banana, white bread)"},
        {"icon": "☕", "when": "90 min before", "what": "Optional: coffee if you use it in training"},
        {"icon": "💧", "when": "Every 5 km", "what": "Water at every aid station"},
        {"icon": "🍬", "when": "At 10 km & 16 km", "what": "Gel or energy chews — use brands you've trained with"},
        {"icon": "🧂", "when": "If hot/humid", "what": "Electrolyte tablet at km 10"},
        {"icon": "🍫", "when": "Within 30 min after", "what": "Protein shake or chocolate milk + carbs"},
    ],
    mental_checkpoints=[
        {"distance": "5 km", "message": "Feel easy? Good — that's the plan. Stay patient."},
        {"distance": "10 km", "message": "One quarter done. Find your rhythm and protect it."},
        {"distance": "16 km", "message": "The halfway point emotionally. This is where half marathons are won."},
        {"distance": "19 km", "message": "Two km left. Dig in — this discomfort is temporary."},
        {"distance": "Finish", "message": "You've earned this. Finish strong."},
    ],
    morning_timeline=[
        ("2.5 hrs before", "Eat pre-race meal (tested in training)"),
        ("2 hrs before", "Arrive at venue, bag drop, bib collection"),
        ("60 min before", "Easy 10-min jog to warm up the engine"),
        ("40 min before", "Dynamic drills: leg swings, hip circles, A-skips"),
        ("20 min before", "2–3 × 30-sec strides at goal pace"),
        ("10 min before", "Corral, final mindset check"),
    ],
)


_30K_TRAIL = RaceProfile(
    distance_km=30.0,
    display_name="30K Trail",
    pacing_strategy=(
        "Trail racing requires effort-based pacing, not pace-based pacing. "
        "Climb hills with power hiking if needed — it's often faster than running uphill. "
        "Run descents confidently — this is where time is made on trails. "
        "Eat and drink earlier than you think you need to."
    ),
    nutrition_timing=[
        {"icon": "🍌", "when": "3 hrs before", "what": "Larger carb meal — you'll need the reserves"},
        {"icon": "🍬", "when": "Every 5–6 km", "what": "Gel or real food (dates, banana pieces) starting at km 8"},
        {"icon": "💧", "when": "Every 3–4 km", "what": "Water — more on climbs, trail runs sweat harder"},
        {"icon": "🧂", "when": "Every 10 km", "what": "Electrolytes — cramps on trails are race-ending"},
        {"icon": "🍫", "when": "Immediately after", "what": "Real food: protein + substantial carbs"},
    ],
    mental_checkpoints=[
        {"distance": "5 km", "message": "First climb. Power hike if needed — no shame in that."},
        {"distance": "15 km", "message": "Halfway. How is fueling going? Eat something now if not recently."},
        {"distance": "22 km", "message": "The hardest part of any trail race. Run your own race, not someone else's."},
        {"distance": "27 km", "message": "3 km to go. The finish line is real — put your head down."},
    ],
    morning_timeline=[
        ("3 hrs before", "Larger pre-race breakfast — you'll burn more than any other distance"),
        ("2 hrs before", "Arrive at venue, gear check (poles if used, hydration vest)"),
        ("60 min before", "Easy hike or jog to warm legs"),
        ("30 min before", "Confirm nutrition plan, take an early gel if long start queue"),
        ("10 min before", "Arrive at start, stay calm"),
    ],
    week_before_extras=[
        "Test run your hydration vest or belt on an easy run",
        "Sharpen or replace trail shoe spikes/lugs if worn",
        "Confirm drop bag rules and pack accordingly",
    ],
)


_MARATHON = RaceProfile(
    distance_km=42.2,
    display_name="Marathon",
    pacing_strategy=(
        "First 10 km: goal pace minus 5–10 sec/km — the hardest discipline in marathon running. "
        "Km 10–30: goal pace. Focus on fueling, staying relaxed, keeping form. "
        "Km 30–40: this is where your training weeks show. Push through. "
        "Final 2.2 km: leave nothing behind."
    ),
    nutrition_timing=[
        {"icon": "🍌", "when": "3 hrs before", "what": "Tested breakfast: oatmeal + banana + white toast"},
        {"icon": "☕", "when": "2 hrs before", "what": "Coffee if trained with it; avoid if not"},
        {"icon": "🍬", "when": "Every 6–7 km from km 8", "what": "Gel every 6–7 km — do NOT skip early gels"},
        {"icon": "💧", "when": "Every aid station", "what": "Water: walk aid stations to drink efficiently"},
        {"icon": "🧂", "when": "At km 15 & 30", "what": "Electrolyte drink or tab — critical after km 25"},
        {"icon": "🍫", "when": "Within 30 min after", "what": "Recovery shake immediately; real meal within 2 hrs"},
    ],
    mental_checkpoints=[
        {"distance": "10 km", "message": "One quarter done. Still feeling fresh? Good — stay conservative."},
        {"distance": "21 km", "message": "Halfway. If you feel great, stay controlled. The race starts at 30 km."},
        {"distance": "30 km", "message": "The wall zone. This is where your training runs matter most. Hold form."},
        {"distance": "35 km", "message": "7 km. Count them down. Everything hurts — keep moving."},
        {"distance": "40 km", "message": "2 km. You will finish. Make these last steps count."},
    ],
    morning_timeline=[
        ("3 hrs before", "Eat tested breakfast — this timing is non-negotiable"),
        ("2 hrs before", "Arrive at venue — marathons have complex logistics"),
        ("90 min before", "Bag drop, porta-loo queue (expect a wait)"),
        ("45 min before", "Easy 5-min jog only — conserve energy"),
        ("20 min before", "Into start corral — find your pace group"),
        ("5 min before", "Deep breaths. Trust your training."),
    ],
    week_before_extras=[
        "Write your goal pace on your wrist or arm in permanent marker",
        "Plan where supporters will be — agree on specific km markers",
        "Prepare a 'Plan B' pace in case the first km feels harder than expected",
    ],
)


RACE_PROFILES: Dict[float, RaceProfile] = {
    5.0:  _5K,
    10.0: _10K,
    21.1: _HALF,
    30.0: _30K_TRAIL,
    42.2: _MARATHON,
}


def lookup_profile(target_distance: float) -> RaceProfile:
    """Return the closest matching road race profile by distance.

    Snaps to the nearest registered profile; for arbitrary trail/ultra
    distances the caller should route to the trail-protocol path before
    reaching this lookup.
    """
    closest_distance = min(RACE_PROFILES.keys(), key=lambda d: abs(d - target_distance))
    return RACE_PROFILES[closest_distance]
